#!/bin/sh
PROFILE=chatch-serverless

STAGE=$1
if [ "${STAGE}" = "" ]; then
  echo "Usage: ssm-create-params <stage>"
  exit 1
fi

CMD="aws --profile $PROFILE ssm put-parameter"

$CMD --name "/$STAGE/paypal-client-id" --value "AZVkx9nNnHWtPwDYNjaxZPhG6lLTZPF2f6JbvI5FEcvCp82aLY2zwuXgmQ6K1ADCWhcfkF-LeEuiTg0X" --type String
$CMD --name "/$STAGE/paypal-client-secret" --value "EEpKWwbz0_jJ_zqw_ul91MaRCaU0vXai3VzGbrds3WEmD1heD9bn7dym84dtNy6gfC7wJLiGR_I2QbQ2" --type String
